import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import re
import pdfplumber
import io

# --- CONFIGURATION ---
st.set_page_config(page_title="VolleyStats Pro", page_icon="🏐", layout="wide")

# --- BACKEND: PARSER WITH DEBUG LOGGING ---
def parse_pdf_match_debug(file):
    """
    Parses the PDF and generates a detailed debug log of every decision made.
    """
    # 1. Extract Raw Text
    full_text = ""
    with pdfplumber.open(file) as pdf:
        for i, page in enumerate(pdf.pages):
            full_text += f"\n--- PAGE {i+1} START ---\n"
            full_text += page.extract_text() + "\n"
            full_text += f"--- PAGE {i+1} END ---\n"

    # Initialize the Debug Log
    debug_log = "=== VOLLEYSTATS DEBUG REPORT ===\n"
    debug_log += "Generated by Streamlit App\n\n"
    
    # 2. Look for Scores
    debug_log += "--- STEP 1: RAW SCORE PATTERN SEARCH ---\n"
    # Regex for "Num-Num" or "Num:Num" or "Num Num"
    # Captures things like "25-22", "20:30", "15 13"
    raw_patterns = re.findall(r'(?<!\d)(\d{1,2})\s*[:\-\s]\s*(\d{1,2})(?!\d)', full_text)
    
    debug_log += f"Found {len(raw_patterns)} potential number pairs: {raw_patterns}\n\n"

    # 3. Filter Logic
    debug_log += "--- STEP 2: FILTERING LOGIC ---\n"
    valid_sets = []
    
    for idx, (s1, s2) in enumerate(raw_patterns):
        try:
            sc_home, sc_away = int(s1), int(s2)
            log_prefix = f"Pair #{idx} ({s1}-{s2}): "
            
            # Filter A: Impossible Scores (>50 usually means stats, not set scores)
            if sc_home > 50 or sc_away > 50:
                debug_log += log_prefix + "REJECTED (Too high, likely total points)\n"
                continue

            # Filter B: Minimum points (Must be at least 15 to be a set)
            # This kills "1-0", "2-1" (set counts) or "00:45" (time)
            if max(sc_home, sc_away) < 15:
                debug_log += log_prefix + "REJECTED (Too low, likely set count or time)\n"
                continue

            # Filter C: Winner Logic (One team must reach 25 or 15, OR be OT)
            is_reg_win = (sc_home == 25 or sc_away == 25)
            is_tie_win = (sc_home == 15 or sc_away == 15)
            is_ot = (sc_home > 24 and sc_away > 24)
            
            if is_reg_win or is_tie_win or is_ot:
                # Check for duplicates (common in PDF parsing)
                if valid_sets and valid_sets[-1]['Home'] == sc_home and valid_sets[-1]['Away'] == sc_away:
                     debug_log += log_prefix + "REJECTED (Exact duplicate of previous)\n"
                else:
                    valid_sets.append({"Home": sc_home, "Away": sc_away})
                    debug_log += log_prefix + "ACCEPTED as Valid Set\n"
            else:
                 debug_log += log_prefix + "REJECTED (No winner reached 25/15 and not OT)\n"

        except ValueError:
            debug_log += f"Pair #{idx}: Error parsing integers.\n"

    # 4. Final Cleanup
    if len(valid_sets) > 5:
        debug_log += "\nWARNING: More than 5 sets found. Truncating to first 5.\n"
        valid_sets = valid_sets[:5]

    debug_log += f"\n--- FINAL EXTRACTED SETS ---\n{valid_sets}\n"
    
    debug_log += "\n--- FULL RAW TEXT DUMP (For AI Analysis) ---\n"
    debug_log += full_text

    return {
        "teams": {"Home": "Home Team (Auto)", "Away": "Away Team (Auto)"},
        "sets": valid_sets,
        "debug_log": debug_log
    }

# --- UTILS: MOCK DATA (For Charts) ---
def generate_mock_stats():
    # Only for visualization, does not affect extraction
    return pd.DataFrame([
        {"Player": "#1", "Efficiency": 0.350, "Attempts": 20, "Kills": 10},
        {"Player": "#2", "Efficiency": 0.150, "Attempts": 15, "Kills": 5},
    ])

# --- FRONTEND ---
def main():
    st.title("🏐 VolleyStats Debugger")
    
    with st.sidebar:
        st.header("1. Upload")
        uploaded_file = st.file_uploader("Upload PDF", type="pdf")
        
        st.divider()
        st.info("Upload a file to generate the Debug Report.")

    if not uploaded_file:
        st.write("Waiting for file...")
        return

    # Process
    data = parse_pdf_match_debug(uploaded_file)
    sets_df = pd.DataFrame(data['sets'])
    
    # Show Download Button for the Log
    st.success("Analysis Complete!")
    
    st.download_button(
        label="📥 Download Debug Report (.txt)",
        data=data['debug_log'],
        file_name="debug_log.txt",
        mime="text/plain",
        help="Send this file to your AI assistant to fix the extraction errors."
    )

    # Preview Extraction
    st.subheader("Extracted Scores")
    if not sets_df.empty:
        sets_df['Set'] = range(1, len(sets_df) + 1)
        st.table(sets_df.set_index('Set'))
    else:
        st.error("No valid sets found. Check the Debug Report.")

    # Show Charts (Proof of Concept)
    if not sets_df.empty:
        st.subheader("Visualizations")
        sets_df['Diff'] = sets_df['Home'] - sets_df['Away']
        fig = px.bar(sets_df, x='Set', y='Diff', title="Score Differential")
        st.plotly_chart(fig)

if __name__ == "__main__":
    main()